spring:
  application:
    name: tmk-batch
  profiles:
    default: dev
  datasource:
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: org.postgresql.Driver
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
    show-sql: false
  batch:
    job:
      enabled: false
    jdbc:
      initialize-schema: always
