spring:
  application:
    name: tmk-batch
  profiles:
    default: dev
  datasource:
    url: ${DB_URL:jdbc:postgresql://localhost:5432/tmk}
    username: ${DB_USERNAME:tmk}
    password: ${DB_PASSWORD:tmk}
    driver-class-name: org.postgresql.Driver
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
    show-sql: false
  batch:
    job:
      enabled: ${BATCH_JOB_ENABLED:false}
    jdbc:
      initialize-schema: ${BATCH_INITIALIZE_SCHEMA:always}
